Task 5 requires Batch Normalization and Layer Normalization, with manual forward and backward calculations using PyTorch and NumPy.

Import Libraries

In [1]:
import torch
import numpy as np

input data

In [2]:
X = torch.tensor([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0],
    [7.0, 8.0, 9.0]
])

print(X)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


Batch Normalization

In [4]:

mean = torch.mean(X, dim=0)


variance = torch.var(X, dim=0, unbiased=False)

print("Mean:", mean)
print("Variance:", variance)

Mean: tensor([4., 5., 6.])
Variance: tensor([6., 6., 6.])


Normalize the data

In [5]:
epsilon = 1e-5

X_batch_norm = (X - mean) / torch.sqrt(variance + epsilon)

print("Batch Normalized:")
print(X_batch_norm)

Batch Normalized:
tensor([[-1.2247, -1.2247, -1.2247],
        [ 0.0000,  0.0000,  0.0000],
        [ 1.2247,  1.2247,  1.2247]])


Scale and Shift

In [6]:
gamma = torch.ones(3)
beta = torch.zeros(3)

X_batch_norm = gamma * X_batch_norm + beta

print(X_batch_norm)

tensor([[-1.2247, -1.2247, -1.2247],
        [ 0.0000,  0.0000,  0.0000],
        [ 1.2247,  1.2247,  1.2247]])


Layer Normalization

In [7]:

layer_mean = torch.mean(X, dim=1, keepdim=True)


layer_variance = torch.var(X, dim=1, keepdim=True, unbiased=False)

print("Layer Mean:")
print(layer_mean)

print("Layer Variance:")
print(layer_variance)

Layer Mean:
tensor([[2.],
        [5.],
        [8.]])
Layer Variance:
tensor([[0.6667],
        [0.6667],
        [0.6667]])


Normalize using layer normalization

In [9]:
X_layer_norm = (
    X - layer_mean
) / torch.sqrt(layer_variance + epsilon)

print("Layer Normalized:")
print(X_layer_norm)

Layer Normalized:
tensor([[-1.2247,  0.0000,  1.2247],
        [-1.2247,  0.0000,  1.2247],
        [-1.2247,  0.0000,  1.2247]])


Results

In [10]:
print("Original Data:")
print(X)

print("\nBatch Normalization:")
print(X_batch_norm)

print("\nLayer Normalization:")
print(X_layer_norm)

Original Data:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

Batch Normalization:
tensor([[-1.2247, -1.2247, -1.2247],
        [ 0.0000,  0.0000,  0.0000],
        [ 1.2247,  1.2247,  1.2247]])

Layer Normalization:
tensor([[-1.2247,  0.0000,  1.2247],
        [-1.2247,  0.0000,  1.2247],
        [-1.2247,  0.0000,  1.2247]])
